tables:
  autoscope_unassigned:
    columns:
      table_name: varchar(128)
      autoscope_objectfields: json
    indices:
      - table_name
  autoscope_users:
    columns:
      username: varchar(128)
      passhash: varchar(128)
      salt: bigint
    indices:
      - username
  autoscope_groups:
    columns:
      name: varchar(128)
  autoscope_user_groups:
    columns:
      user_id: bigint
      group_id: bigint
    indices:
      - user_id
      - group_id
  autoscope_table_groups:
    columns:
      table_name: varchar(128)
      group_id: bigint
    indices:
      - table_name
      - group_id
  autoscope_user_sessions:
    columns:
      time: bigint
      username: varchar(128)
      session_id: varchar(128)
    indices:
      - username
      - time
  autoscope_table_stats:
    columns:
      table_name: varchar(128)
      insert_queries: bigint
      select_queries: bigint
      update_queries: bigint
    indices:
      - table_name
  autoscope_restriction_stats:
    columns:
      table_name: varchar(128)
      restriction: varchar(128)
      queries: bigint
    indices:
      - table_name
      - restriction
  autoscope_objectfield_stats:
    columns:
      table_name: varchar(128)
      object_field_name: varchar(128)
      type: varchar(128)
      occurrences: bigint
    indices:
      - table_name
  autoscope_foreignkey_stats:
    columns:
      table_name: varchar(128)
      object_field_name: varchar(128)
      foreign_table_name: varchar(128)
      occurrences: bigint
    indices:
      - table_name
